import type { Metadata } from 'next';
import '@/shared/styles/color.css';
import './globals.css';

import { pretendard } from '@/shared/styles/font';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko" className={pretendard.variable}>
      <body>{children}</body>
    </html>
  );
}
